name: Control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8

      - name: Run tests
        run: |
          pytest

      - name: Run flake8
        uses: py-actions/flake8@v2